/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.GeoPointResource;
import java.util.UUID;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class AnonymizedUserResource  {
  
  @SerializedName("centerOfLocationGeoHash")
  private GeoPointResource centerOfLocationGeoHash = null;
  @SerializedName("city")
  private String city = null;
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("id")
  private UUID id = null;
  @SerializedName("locationGeoHash")
  private String locationGeoHash = null;
  public enum SourceEnum {
     HOTLINE,  APP, 
  };
  @SerializedName("source")
  private SourceEnum source = null;
  @SerializedName("zipCode")
  private String zipCode = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public GeoPointResource getCenterOfLocationGeoHash() {
    return centerOfLocationGeoHash;
  }
  public void setCenterOfLocationGeoHash(GeoPointResource centerOfLocationGeoHash) {
    this.centerOfLocationGeoHash = centerOfLocationGeoHash;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getLocationGeoHash() {
    return locationGeoHash;
  }
  public void setLocationGeoHash(String locationGeoHash) {
    this.locationGeoHash = locationGeoHash;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public SourceEnum getSource() {
    return source;
  }
  public void setSource(SourceEnum source) {
    this.source = source;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getZipCode() {
    return zipCode;
  }
  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnonymizedUserResource anonymizedUserResource = (AnonymizedUserResource) o;
    return (centerOfLocationGeoHash == null ? anonymizedUserResource.centerOfLocationGeoHash == null : centerOfLocationGeoHash.equals(anonymizedUserResource.centerOfLocationGeoHash)) &&
        (city == null ? anonymizedUserResource.city == null : city.equals(anonymizedUserResource.city)) &&
        (firstName == null ? anonymizedUserResource.firstName == null : firstName.equals(anonymizedUserResource.firstName)) &&
        (id == null ? anonymizedUserResource.id == null : id.equals(anonymizedUserResource.id)) &&
        (locationGeoHash == null ? anonymizedUserResource.locationGeoHash == null : locationGeoHash.equals(anonymizedUserResource.locationGeoHash)) &&
        (source == null ? anonymizedUserResource.source == null : source.equals(anonymizedUserResource.source)) &&
        (zipCode == null ? anonymizedUserResource.zipCode == null : zipCode.equals(anonymizedUserResource.zipCode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (centerOfLocationGeoHash == null ? 0: centerOfLocationGeoHash.hashCode());
    result = 31 * result + (city == null ? 0: city.hashCode());
    result = 31 * result + (firstName == null ? 0: firstName.hashCode());
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (locationGeoHash == null ? 0: locationGeoHash.hashCode());
    result = 31 * result + (source == null ? 0: source.hashCode());
    result = 31 * result + (zipCode == null ? 0: zipCode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnonymizedUserResource {\n");
    
    sb.append("  centerOfLocationGeoHash: ").append(centerOfLocationGeoHash).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  locationGeoHash: ").append(locationGeoHash).append("\n");
    sb.append("  source: ").append(source).append("\n");
    sb.append("  zipCode: ").append(zipCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
