/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.CreateOrderItemDto;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class CreateOrderDto  {
  
  @SerializedName("hint")
  private String hint = null;
  @SerializedName("maxPrice")
  private Integer maxPrice = null;
  @SerializedName("userId")
  private Integer userId = null;
  @SerializedName("items")
  private List<CreateOrderItemDto> items = null;
  public enum SourceEnum {
     HOTLINE,  APP, 
  };
  @SerializedName("source")
  private SourceEnum source = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHint() {
    return hint;
  }
  public void setHint(String hint) {
    this.hint = hint;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxPrice() {
    return maxPrice;
  }
  public void setMaxPrice(Integer maxPrice) {
    this.maxPrice = maxPrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getUserId() {
    return userId;
  }
  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CreateOrderItemDto> getItems() {
    return items;
  }
  public void setItems(List<CreateOrderItemDto> items) {
    this.items = items;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public SourceEnum getSource() {
    return source;
  }
  public void setSource(SourceEnum source) {
    this.source = source;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrderDto createOrderDto = (CreateOrderDto) o;
    return (hint == null ? createOrderDto.hint == null : hint.equals(createOrderDto.hint)) &&
        (maxPrice == null ? createOrderDto.maxPrice == null : maxPrice.equals(createOrderDto.maxPrice)) &&
        (userId == null ? createOrderDto.userId == null : userId.equals(createOrderDto.userId)) &&
        (items == null ? createOrderDto.items == null : items.equals(createOrderDto.items)) &&
        (source == null ? createOrderDto.source == null : source.equals(createOrderDto.source));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (hint == null ? 0: hint.hashCode());
    result = 31 * result + (maxPrice == null ? 0: maxPrice.hashCode());
    result = 31 * result + (userId == null ? 0: userId.hashCode());
    result = 31 * result + (items == null ? 0: items.hashCode());
    result = 31 * result + (source == null ? 0: source.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrderDto {\n");
    
    sb.append("  hint: ").append(hint).append("\n");
    sb.append("  maxPrice: ").append(maxPrice).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  items: ").append(items).append("\n");
    sb.append("  source: ").append(source).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
