/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.GeoPointResource1;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class CreateUserDto  {
  
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("lastName")
  private String lastName = null;
  @SerializedName("street")
  private String street = null;
  @SerializedName("streetNo")
  private String streetNo = null;
  @SerializedName("zipCode")
  private String zipCode = null;
  @SerializedName("city")
  private String city = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("location")
  private GeoPointResource1 location = null;
  @SerializedName("phone")
  private String phone = null;
  public enum SourceEnum {
     HOTLINE,  APP, 
  };
  @SerializedName("source")
  private SourceEnum source = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStreet() {
    return street;
  }
  public void setStreet(String street) {
    this.street = street;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStreetNo() {
    return streetNo;
  }
  public void setStreetNo(String streetNo) {
    this.streetNo = streetNo;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getZipCode() {
    return zipCode;
  }
  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public GeoPointResource1 getLocation() {
    return location;
  }
  public void setLocation(GeoPointResource1 location) {
    this.location = location;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public SourceEnum getSource() {
    return source;
  }
  public void setSource(SourceEnum source) {
    this.source = source;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateUserDto createUserDto = (CreateUserDto) o;
    return (firstName == null ? createUserDto.firstName == null : firstName.equals(createUserDto.firstName)) &&
        (lastName == null ? createUserDto.lastName == null : lastName.equals(createUserDto.lastName)) &&
        (street == null ? createUserDto.street == null : street.equals(createUserDto.street)) &&
        (streetNo == null ? createUserDto.streetNo == null : streetNo.equals(createUserDto.streetNo)) &&
        (zipCode == null ? createUserDto.zipCode == null : zipCode.equals(createUserDto.zipCode)) &&
        (city == null ? createUserDto.city == null : city.equals(createUserDto.city)) &&
        (email == null ? createUserDto.email == null : email.equals(createUserDto.email)) &&
        (location == null ? createUserDto.location == null : location.equals(createUserDto.location)) &&
        (phone == null ? createUserDto.phone == null : phone.equals(createUserDto.phone)) &&
        (source == null ? createUserDto.source == null : source.equals(createUserDto.source));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (firstName == null ? 0: firstName.hashCode());
    result = 31 * result + (lastName == null ? 0: lastName.hashCode());
    result = 31 * result + (street == null ? 0: street.hashCode());
    result = 31 * result + (streetNo == null ? 0: streetNo.hashCode());
    result = 31 * result + (zipCode == null ? 0: zipCode.hashCode());
    result = 31 * result + (city == null ? 0: city.hashCode());
    result = 31 * result + (email == null ? 0: email.hashCode());
    result = 31 * result + (location == null ? 0: location.hashCode());
    result = 31 * result + (phone == null ? 0: phone.hashCode());
    result = 31 * result + (source == null ? 0: source.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateUserDto {\n");
    
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  street: ").append(street).append("\n");
    sb.append("  streetNo: ").append(streetNo).append("\n");
    sb.append("  zipCode: ").append(zipCode).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  location: ").append(location).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  source: ").append(source).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
