/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.OrderItemResource;
import java.util.*;
import java.util.Date;
import java.util.UUID;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class OrderResource  {
  
  @SerializedName("createdAt")
  private Date createdAt = null;
  @SerializedName("hint")
  private String hint = null;
  @SerializedName("id")
  private UUID id = null;
  @SerializedName("items")
  private List<OrderItemResource> items = null;
  @SerializedName("maxPrice")
  private Integer maxPrice = null;
  public enum SourceEnum {
     HOTLINE,  APP, 
  };
  @SerializedName("source")
  private SourceEnum source = null;
  public enum StatusEnum {
     TO_BE_DELIVERED,  DELIVERED,  CONSUMER_CANCELLED,  ACCEPTED, 
  };
  @SerializedName("status")
  private StatusEnum status = null;
  @SerializedName("updatedAt")
  private Date updatedAt = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHint() {
    return hint;
  }
  public void setHint(String hint) {
    this.hint = hint;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<OrderItemResource> getItems() {
    return items;
  }
  public void setItems(List<OrderItemResource> items) {
    this.items = items;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxPrice() {
    return maxPrice;
  }
  public void setMaxPrice(Integer maxPrice) {
    this.maxPrice = maxPrice;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public SourceEnum getSource() {
    return source;
  }
  public void setSource(SourceEnum source) {
    this.source = source;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderResource orderResource = (OrderResource) o;
    return (createdAt == null ? orderResource.createdAt == null : createdAt.equals(orderResource.createdAt)) &&
        (hint == null ? orderResource.hint == null : hint.equals(orderResource.hint)) &&
        (id == null ? orderResource.id == null : id.equals(orderResource.id)) &&
        (items == null ? orderResource.items == null : items.equals(orderResource.items)) &&
        (maxPrice == null ? orderResource.maxPrice == null : maxPrice.equals(orderResource.maxPrice)) &&
        (source == null ? orderResource.source == null : source.equals(orderResource.source)) &&
        (status == null ? orderResource.status == null : status.equals(orderResource.status)) &&
        (updatedAt == null ? orderResource.updatedAt == null : updatedAt.equals(orderResource.updatedAt));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (createdAt == null ? 0: createdAt.hashCode());
    result = 31 * result + (hint == null ? 0: hint.hashCode());
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (items == null ? 0: items.hashCode());
    result = 31 * result + (maxPrice == null ? 0: maxPrice.hashCode());
    result = 31 * result + (source == null ? 0: source.hashCode());
    result = 31 * result + (status == null ? 0: status.hashCode());
    result = 31 * result + (updatedAt == null ? 0: updatedAt.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderResource {\n");
    
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  hint: ").append(hint).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  items: ").append(items).append("\n");
    sb.append("  maxPrice: ").append(maxPrice).append("\n");
    sb.append("  source: ").append(source).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
