/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.OrderResource;
import io.swagger.client.model.UserResource;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class UserOrderResponse  {
  
  @SerializedName("driver")
  private UserResource driver = null;
  @SerializedName("order")
  private OrderResource order = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public UserResource getDriver() {
    return driver;
  }
  public void setDriver(UserResource driver) {
    this.driver = driver;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public OrderResource getOrder() {
    return order;
  }
  public void setOrder(OrderResource order) {
    this.order = order;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserOrderResponse userOrderResponse = (UserOrderResponse) o;
    return (driver == null ? userOrderResponse.driver == null : driver.equals(userOrderResponse.driver)) &&
        (order == null ? userOrderResponse.order == null : order.equals(userOrderResponse.order));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (driver == null ? 0: driver.hashCode());
    result = 31 * result + (order == null ? 0: order.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserOrderResponse {\n");
    
    sb.append("  driver: ").append(driver).append("\n");
    sb.append("  order: ").append(order).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
