/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.GeoPointResource;
import java.util.Date;
import java.util.UUID;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class UserResource  {
  
  @SerializedName("city")
  private String city = null;
  @SerializedName("createdAt")
  private Date createdAt = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("id")
  private UUID id = null;
  @SerializedName("lastName")
  private String lastName = null;
  @SerializedName("location")
  private GeoPointResource location = null;
  @SerializedName("locationGeoHash")
  private String locationGeoHash = null;
  @SerializedName("phone")
  private String phone = null;
  public enum SourceEnum {
     HOTLINE,  APP, 
  };
  @SerializedName("source")
  private SourceEnum source = null;
  @SerializedName("street")
  private String street = null;
  @SerializedName("streetNo")
  private String streetNo = null;
  @SerializedName("updatedAt")
  private Date updatedAt = null;
  @SerializedName("zipCode")
  private String zipCode = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public GeoPointResource getLocation() {
    return location;
  }
  public void setLocation(GeoPointResource location) {
    this.location = location;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getLocationGeoHash() {
    return locationGeoHash;
  }
  public void setLocationGeoHash(String locationGeoHash) {
    this.locationGeoHash = locationGeoHash;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public SourceEnum getSource() {
    return source;
  }
  public void setSource(SourceEnum source) {
    this.source = source;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStreet() {
    return street;
  }
  public void setStreet(String street) {
    this.street = street;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStreetNo() {
    return streetNo;
  }
  public void setStreetNo(String streetNo) {
    this.streetNo = streetNo;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getZipCode() {
    return zipCode;
  }
  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserResource userResource = (UserResource) o;
    return (city == null ? userResource.city == null : city.equals(userResource.city)) &&
        (createdAt == null ? userResource.createdAt == null : createdAt.equals(userResource.createdAt)) &&
        (email == null ? userResource.email == null : email.equals(userResource.email)) &&
        (firstName == null ? userResource.firstName == null : firstName.equals(userResource.firstName)) &&
        (id == null ? userResource.id == null : id.equals(userResource.id)) &&
        (lastName == null ? userResource.lastName == null : lastName.equals(userResource.lastName)) &&
        (location == null ? userResource.location == null : location.equals(userResource.location)) &&
        (locationGeoHash == null ? userResource.locationGeoHash == null : locationGeoHash.equals(userResource.locationGeoHash)) &&
        (phone == null ? userResource.phone == null : phone.equals(userResource.phone)) &&
        (source == null ? userResource.source == null : source.equals(userResource.source)) &&
        (street == null ? userResource.street == null : street.equals(userResource.street)) &&
        (streetNo == null ? userResource.streetNo == null : streetNo.equals(userResource.streetNo)) &&
        (updatedAt == null ? userResource.updatedAt == null : updatedAt.equals(userResource.updatedAt)) &&
        (zipCode == null ? userResource.zipCode == null : zipCode.equals(userResource.zipCode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (city == null ? 0: city.hashCode());
    result = 31 * result + (createdAt == null ? 0: createdAt.hashCode());
    result = 31 * result + (email == null ? 0: email.hashCode());
    result = 31 * result + (firstName == null ? 0: firstName.hashCode());
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (lastName == null ? 0: lastName.hashCode());
    result = 31 * result + (location == null ? 0: location.hashCode());
    result = 31 * result + (locationGeoHash == null ? 0: locationGeoHash.hashCode());
    result = 31 * result + (phone == null ? 0: phone.hashCode());
    result = 31 * result + (source == null ? 0: source.hashCode());
    result = 31 * result + (street == null ? 0: street.hashCode());
    result = 31 * result + (streetNo == null ? 0: streetNo.hashCode());
    result = 31 * result + (updatedAt == null ? 0: updatedAt.hashCode());
    result = 31 * result + (zipCode == null ? 0: zipCode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserResource {\n");
    
    sb.append("  city: ").append(city).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  location: ").append(location).append("\n");
    sb.append("  locationGeoHash: ").append(locationGeoHash).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  source: ").append(source).append("\n");
    sb.append("  street: ").append(street).append("\n");
    sb.append("  streetNo: ").append(streetNo).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("  zipCode: ").append(zipCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
