/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.AnonymizedUserResource;
import io.swagger.client.model.OrderResource;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class UserOrderSearchResponse  {
  
  @SerializedName("order")
  private OrderResource order = null;
  @SerializedName("user")
  private AnonymizedUserResource user = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public OrderResource getOrder() {
    return order;
  }
  public void setOrder(OrderResource order) {
    this.order = order;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public AnonymizedUserResource getUser() {
    return user;
  }
  public void setUser(AnonymizedUserResource user) {
    this.user = user;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserOrderSearchResponse userOrderSearchResponse = (UserOrderSearchResponse) o;
    return (order == null ? userOrderSearchResponse.order == null : order.equals(userOrderSearchResponse.order)) &&
        (user == null ? userOrderSearchResponse.user == null : user.equals(userOrderSearchResponse.user));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (order == null ? 0: order.hashCode());
    result = 31 * result + (user == null ? 0: user.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserOrderSearchResponse {\n");
    
    sb.append("  order: ").append(order).append("\n");
    sb.append("  user: ").append(user).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
