/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package jetzt.machbarschaft.android.api.model

import com.squareup.moshi.Json

/**
 *
 * @param centerOfLocationGeoHash
 * @param city
 * @param locationGeoHash
 * @param source
 * @param zipCode
 * @param firstName
 * @param id
 */

data class AnonymizedUserResourceModel(
    @Json(name = "centerOfLocationGeoHash")
    val centerOfLocationGeoHash: GeoPointResourceModel,
    @Json(name = "city")
    val city: kotlin.String,
    @Json(name = "locationGeoHash")
    val locationGeoHash: kotlin.String,
    @Json(name = "source")
    val source: AnonymizedUserResourceModel.Source,
    @Json(name = "zipCode")
    val zipCode: kotlin.String,
    @Json(name = "firstName")
    val firstName: kotlin.String? = null,
    @Json(name = "id")
    val id: java.util.UUID? = null
) {

    /**
     *
     * Values: hOTLINE,aPP
     */

    enum class Source(val value: kotlin.String) {
        @Json(name = "HOTLINE")
        hOTLINE("HOTLINE"),
        @Json(name = "APP")
        aPP("APP");
    }
}

