/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package jetzt.machbarschaft.android.api.model


import com.squareup.moshi.Json

/**
 *
 * @param prefetch
 */

data class FluxUserOrderResponseModel(
    @Json(name = "prefetch")
    val prefetch: kotlin.Int? = null
)

