/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package jetzt.machbarschaft.android.api.model


import com.squareup.moshi.Json

/**
 *
 * @param latitude
 * @param longitude
 */

data class GeoPointResourceModel(
    @Json(name = "latitude")
    val latitude: kotlin.Double,
    @Json(name = "longitude")
    val longitude: kotlin.Double
)

