/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package jetzt.machbarschaft.android.api.model


import com.squareup.moshi.Json

/**
 *
 * @param createdAt
 * @param description
 * @param updatedAt
 * @param id
 */

data class OrderItemResourceModel(
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,
    @Json(name = "id")
    val id: java.util.UUID? = null
)

