/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package jetzt.machbarschaft.android.api.model

import com.squareup.moshi.Json

/**
 *
 * @param createdAt
 * @param items
 * @param source
 * @param status
 * @param updatedAt
 * @param hint
 * @param id
 * @param maxPrice
 */

data class OrderResourceModel(
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,
    @Json(name = "items")
    val items: kotlin.Array<OrderItemResourceModel>,
    @Json(name = "source")
    val source: OrderResourceModel.Source,
    @Json(name = "status")
    val status: OrderResourceModel.Status,
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,
    @Json(name = "hint")
    val hint: kotlin.String? = null,
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "maxPrice")
    val maxPrice: kotlin.Int? = null
) {

    /**
     *
     * Values: hOTLINE,aPP
     */

    enum class Source(val value: kotlin.String) {
        @Json(name = "HOTLINE")
        hOTLINE("HOTLINE"),
        @Json(name = "APP")
        aPP("APP");
    }

    /**
     *
     * Values: tOBEDELIVERED,dELIVERED,cONSUMERCANCELLED,aCCEPTED
     */

    enum class Status(val value: kotlin.String) {
        @Json(name = "TO_BE_DELIVERED")
        tOBEDELIVERED("TO_BE_DELIVERED"),
        @Json(name = "DELIVERED")
        dELIVERED("DELIVERED"),
        @Json(name = "CONSUMER_CANCELLED")
        cONSUMERCANCELLED("CONSUMER_CANCELLED"),
        @Json(name = "ACCEPTED")
        aCCEPTED("ACCEPTED");
    }
}

