/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package jetzt.machbarschaft.android.api.model

import com.squareup.moshi.Json

/**
 *
 * @param order
 * @param user
 */

data class UserOrderSearchResponseModel(
    @Json(name = "order")
    val order: OrderResourceModel,
    @Json(name = "user")
    val user: AnonymizedUserResourceModel
)

